theme: minima
title: Lisa Demske, Technical Writer
header_pages:
  - about.md
  - writing-samples.md
  - resume.md
minima:
  social_links:
    - { platform: "linkedin",  user_url: "https://linkedin.com/in/lisademske/" }
